#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 重点用能数据上传
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Gra")]
	public partial class energyDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public energyDbDataContext() : 
				base(global::重点用能数据上传.Properties.Settings.Default.LocalDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public energyDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public energyDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public energyDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public energyDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<energyData> energyData
		{
			get
			{
				return this.GetTable<energyData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.energyData")]
	public partial class energyData
	{
		
		private string _dataCode;
		
		private float _dataValue;
		
		private int _inputType;
		
		private int _statType;
		
		private string _statDate;
		
		private string _uploadDate;
		
		private int _scope;
		
		private bool _valid;
		
		public energyData()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string dataCode
		{
			get
			{
				return this._dataCode;
			}
			set
			{
				if ((this._dataCode != value))
				{
					this._dataCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataValue", DbType="Real NOT NULL")]
		public float dataValue
		{
			get
			{
				return this._dataValue;
			}
			set
			{
				if ((this._dataValue != value))
				{
					this._dataValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inputType", DbType="Int NOT NULL")]
		public int inputType
		{
			get
			{
				return this._inputType;
			}
			set
			{
				if ((this._inputType != value))
				{
					this._inputType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statType", DbType="Int NOT NULL")]
		public int statType
		{
			get
			{
				return this._statType;
			}
			set
			{
				if ((this._statType != value))
				{
					this._statType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_statDate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string statDate
		{
			get
			{
				return this._statDate;
			}
			set
			{
				if ((this._statDate != value))
				{
					this._statDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uploadDate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string uploadDate
		{
			get
			{
				return this._uploadDate;
			}
			set
			{
				if ((this._uploadDate != value))
				{
					this._uploadDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scope", DbType="Int NOT NULL")]
		public int scope
		{
			get
			{
				return this._scope;
			}
			set
			{
				if ((this._scope != value))
				{
					this._scope = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valid", DbType="Bit NOT NULL")]
		public bool valid
		{
			get
			{
				return this._valid;
			}
			set
			{
				if ((this._valid != value))
				{
					this._valid = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
